// components/Socials.tsx
import React from 'react';
import socials from '@/data/socials.json';
import { Social } from '@/types';

const Socials: React.FC = () => {
    return (
        <div className="z-50 absolute bottom-0 grid grid-cols-3 gap-12 p-8">
            {socials.map((so: Social) => (
                <a key={so.alt} href={so.url} target="_blank" rel="noopener noreferrer" className="w-10 h-10">
                    <img src={so.icon} alt={so.alt} />
                </a>
            ))}
        </div>
    );
};

export default Socials;

// src/components/Socials.vue
<template>
  <div>
    <a v-for="so in socials" :href="so.url" target="_blank" :key="so.alt">
      <img :src="so.icon" :alt="so.alt">
    </a>
  </div>
</template>

<script lang="ts">
import socials from '@/data/socials.json'
import type {Social} from "@/types"

export default {
  name: "Socials",
  data() {
    return {
      socials: socials as Social[]
    };
  }
};
</script>

<style scoped>

  div {
    @apply z-50 absolute bottom-0 grid grid-cols-3 gap-12 p-8
  }
  a {
    @apply w-10 h-10;
  }

</style>
